# Generated by Django 6.0.3 on 2026-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
