# Generated by Django 6.0.3 on 2026-04-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_academicyear_alter_team_departments_alter_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='user',
            name='expected_graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
