# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_admission_year_user_expected_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dropout',
            field=models.BooleanField(default=False),
        ),
    ]
