# Generated by Django 6.0.3 on 2026-04-21 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_user_admission_year_user_expected_graduation_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('rules', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active programs are visible to students.')),
                ('is_graduate_restricted', models.BooleanField(default=True, help_text='If True, students who have graduated (is_alumni=True) cannot participate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['academic_year__year', 'name'],
                'unique_together': {('academic_year', 'name')},
            },
        ),
    ]
