# Generated by Django 6.0.3 on 2026-04-21 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_admission_year_user_expected_graduation_year_and_more'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artsprogram',
            options={'ordering': ['-arts_fest__year', 'name']},
        ),
        migrations.AddField(
            model_name='artsprogram',
            name='eligible_batches',
            field=models.ManyToManyField(blank=True, help_text='Select the student admission-year batches allowed to participate (e.g. 2023-26, 2024-27). Leave empty to allow ALL current students.', related_name='eligible_programs', to='accounts.academicyear'),
        ),
        migrations.AlterField(
            model_name='artsprogram',
            name='is_graduate_restricted',
            field=models.BooleanField(default=True, help_text='If True, alumni / graduated students cannot participate.'),
        ),
        migrations.CreateModel(
            name='ArtsFest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(help_text='The year the Arts Fest is conducted in.')),
                ('max_programs_per_student', models.PositiveIntegerField(default=3, help_text='Max items a student can participate in')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_arts_fests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='artsprogram',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='artsprogram',
            name='arts_fest',
            field=models.ForeignKey(blank=True, help_text='The Arts Fest this program is held in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.artsfest'),
        ),
        migrations.AlterUniqueTogether(
            name='artsprogram',
            unique_together={('arts_fest', 'name')},
        ),
        migrations.RemoveField(
            model_name='artsprogram',
            name='academic_year',
        ),
    ]
