# Generated by Django 6.0.3 on 2026-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_artsprogram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsprogram',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
