# Generated by Django 6.0.3 on 2026-04-27 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_artsprogram_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsprogram',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artsprogram',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artsprogram',
            name='rules',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artsprogram',
            name='venue',
            field=models.CharField(max_length=200),
        ),
    ]
