# Generated by Django 6.0.3 on 2026-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_artsprogram_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsprogram',
            name='is_team_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artsprogram',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artsprogram',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Max items a team can participate in', null=True),
        ),
    ]
