# Generated by Django 6.0.3 on 2026-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_artsprogram_is_team_based_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsprogram',
            name='event_image',
            field=models.ImageField(blank=True, default='/event_images/default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
