# Generated by Django 6.0.3 on 2026-04-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_artsprogram_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsprogram',
            name='event_image',
            field=models.FileField(blank=True, default='/event_images/default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
