# Generated by Django 6.0.3 on 2026-04-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_artsprogram_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsprogram',
            name='arts_fest',
            field=models.ForeignKey(default=1, help_text='The Arts Fest this program is held in.', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.artsfest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artsprogram',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants allowed', null=True),
        ),
    ]
