# Generated by Django 6.0.3 on 2026-04-21 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participation', '0001_initial'),
        ('programs', '0002_alter_artsprogram_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='arts_fest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='programs.artsfest'),
        ),
        migrations.AddField(
            model_name='participation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='programs.artsprogram'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'program')},
        ),
    ]
