# Generated by Django 6.0.3 on 2026-04-27 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text='For team events, the students participating in this group.', related_name='team_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
