# Generated by Django 6.0.3 on 2026-04-29 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_is_approved'),
        ('scores', '0002_score_judge_score_obtained_score_score_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='accounts.department'),
        ),
    ]
