# Generated by Django 6.0.3 on 2026-04-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_score_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='department',
        ),
    ]
